juntossomosmais/venice

- README.md
> docs: change link to LinkedIn

- packages/core/models/button.model.ts
- packages/core/storybook/knobs/button.ts
- packages/react-ds/src/components/Button/Button.spec.tsx
- packages/react-ds/src/components/Button/Button.stories.mdx
- packages/react-ds/src/components/Button/Button.tsx
- packages/styles/components/Button.module.scss
- packages/vue-ds/src/components/Button/Button.spec.tsx
- packages/vue-ds/src/components/Button/Button.stories.mdx
- packages/vue-ds/src/components/Button/Button.vue
This PR is to add a new option to button component: `shape` 🥇
> feat: add circle's button

- packages/core/storybook/stories/1_Theming.stories.mdx
- packages/core/storybook/stories/2_Screens.stories.mdx
- packages/styles/components/Button.module.scss
- packages/styles/components/Stepper.module.scss
- packages/styles/core/variables.scss
- packages/styles/global/variables.css
This pull-request add some variables about screen and devices to improve the use of breakpoints 
😄 🏆
> feat: add screen variables

- packages/core/storybook/stories/2_Screens.stories.mdx
- packages/styles/global/variables.css
Just a fix on `screen max container` size.
> fix: change screen max container

- packages/react-ds/src/components/Button/Button.spec.tsx
- packages/react-ds/src/components/Button/Button.tsx
- packages/vue-ds/src/components/Button/Button.spec.tsx
Thanks for your help @brunobertolini 😄
> fix: add lost href inside <a>

- packages/core/models/button.model.ts
- packages/core/storybook/knobs/button.ts
- packages/react-ds/src/components/Button/Button.spec.tsx
- packages/react-ds/src/components/Button/Button.stories.mdx
- packages/react-ds/src/components/Button/Button.tsx
- packages/styles/components/Button.module.scss
- packages/vue-ds/src/components/Button/Button.spec.tsx
- packages/vue-ds/src/components/Button/Button.stories.mdx
- packages/vue-ds/src/components/Button/Button.vue
> feat: set large size as default and add medium button

- packages/react-ds/src/components/Pagination/Pagination.tsx
- packages/react-ds/src/components/Stepper/Stepper.tsx
Including `...props` on Pagination and Stepper components.
> chore: including ...props

- packages/vue-ds/package.json
- packages/vue-ds/src/index.ts
> fix: change path to generated build on vue

- README.md
- packages/react-ds/src/components/Button/Button.tsx
- packages/react-ds/src/components/SplitButton/SplitButton.tsx
- packages/react-ds/src/components/Stepper/Stepper.tsx
- packages/styles/components/Button.module.scss
- packages/styles/components/SplitButton.module.scss
- packages/vue-ds/package.json
- packages/vue-ds/src/components/Button/Button.spec.tsx
- packages/vue-ds/src/components/Button/Button.vue
- packages/vue-ds/src/components/SplitButton/SplitButton.spec.tsx
- packages/vue-ds/src/components/SplitButton/SplitButton.vue
- packages/vue-ds/src/components/Stepper/Stepper.spec.tsx
- packages/vue-ds/src/components/Stepper/Stepper.vue
- packages/vue-ds/tsconfig.json
About tests, classnames and commands.
> fix: minimal adjusts to improve projects

- packages/core/storybook/stories/2_Colors.stories.mdx
Reordering context colors to give more prominence
> refactor: reordering context colors

- packages/react-ds/src/components/Alert/index.tsx
- packages/styles/components/Alert.module.scss
Ajustes no css pra importar dentro do projeto Colosseum
<table>
<tr>
<td>Antes</td>
<td>Depois</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
> Fixing alert

- packages/core/storybook/knobs/progress.ts
- packages/react-ds/src/components/Progress/Progress.wrapper.tsx
- packages/react-ds/src/components/Progress/index.spec.tsx
- packages/react-ds/src/components/Progress/index.stories.mdx
- packages/venice-types/src/IProgress.ts
applying the rule of three on the progress display
> Fix: progress display

- packages/react-ds/src/components/Checkbox/index.tsx
- packages/styles/components/CheckboxRadio.module.scss
> fix: remove unnecessary css

- packages/venice-icons/config.json
Adicionado dois novos icones do Font Awesome
n/a
reverter merge
> feat: added two icons from FA

- .github/pull_request_template.md
[Trigger ](https://juntossomosmais.slack.com/archives/CLP6B13J5/p1606323627017000)
update GitHub's template.
> chore: update template

- packages/venice-icons/config.json
[Task](https://juntossomosmais.monday.com/boards/359803983/pulses/901210978)
adding `info icon`
Now, we can use a info icon at projects
Fix master branch
> chore: add new icon

- packages/core/storybook/stories/2_Typography.stories.mdx
- packages/styles/global/variables.scss
[Slack Thread](https://juntossomosmais.slack.com/archives/CLP6B13J5/p1631640515031200)
Creating font-weight variables for when its need to be used without typography vars.
To standardization of font-weight  across the products.
Reverse the merge
Media(images, gifs or videos) that shows the result of your work.
> feat: add weight variables for general use

- packages/styles/global/variables.scss
Change main text color used on projects
Change `#4a4a4a` to `#333333`
> feat(variables): change main text color

- .github/dependabot.yml
[Link da task](https://juntossomosmais.monday.com/boards/XXX/pulses/XXX)
Adiiconado arquivo de configuração do dependabot.
n/d
reverter merge
> feat: added dependabot config file

- packages/react-ds/src/components/Button/index.spec.tsx
- packages/react-ds/src/components/Button/index.stories.mdx
- packages/react-ds/src/components/Button/index.tsx
- packages/styles/components/Button.module.scss
- packages/styles/global/variables.scss
- Button color white option
- Component Button in react-ds
- Revert merge
> feat: button color white

- packages/styles/global/variables.scss
[Task](https://juntossomosmais.monday.com/boards/XXX/pulses/XXX)
New color variables added to global variables file.
- New variables disponible in project to use.
Revert
> feat: add new color variables

- packages/core/storybook/stories/2_Colors.stories.mdx
- packages/styles/global/variables.scss
[Task](https://juntossomosmais.monday.com/boards/2413187753/pulses/2647640850)
Adding new neutral colors and updating documentation
- BU can start using new neutral colors
- DOCs using the right color variables
change after merge
> chore: add new colors and update docs

- packages/core/storybook/stories/2_Colors.stories.mdx
- packages/styles/global/variables.scss
[Task](https://juntossomosmais.monday.com/boards/XXX/pulses/XXX)
Adição da cor Turquesa nas váriaveis. 
Describe what impacts this delivery has and whether it can cause side effects in other parts of the application.
Describe which plan we should follow if this delivery has to be reversed.
Media(images, gifs or videos) that shows the result of your work.
> feat: add turquoise color

- packages/core/storybook/stories/2_Screens.stories.mdx
- packages/styles/core/screens.scss
- packages/styles/global/variables.scss
[Task](https://juntossomosmais.monday.com/boards/1809207165)
New variables to huge screens definitions.
It allow use new variables of screens sizes.
Describe which plan we should follow if this delivery has to be reversed.
Media(images, gifs or videos) that shows the result of your work.
> chore: new variables to huge screens
